name: Build & upload to Amazon Developer Console 

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: build release 
      run: ./gradlew assembleRelease
    - name: Upload to the Amazon AppStore
      uses: ALJAZEERAPLUS/amazon-appstore-action@v1.1.1
      with:
        client-id: ${{secrets.AMAZON_APPSTORE_CLIENT_ID}}
        client-secret: ${{secrets.AMAZON_APPSTORE_CLIENT_SECRET}}
        app-id: ${{ secrets.AMAZON_APPSTORE_APP_ID }}
        apk-file: app/build/outputs/apk/release/app-release.apk
